// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw0ebBJ0dbgkGKN5n4P51jK6tr2emoyQ8',
    appId: '1:972192467262:android:58452a11643bb7e13d046f',
    messagingSenderId: '972192467262',
    projectId: 'breadandword',
    databaseURL: 'https://breadandword-default-rtdb.firebaseio.com',
    storageBucket: 'breadandword.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-2NQ4QMqg-mYk5a3zdYwn9Dd5WQrGiU',
    appId: '1:972192467262:ios:94415047aac22cd73d046f',
    messagingSenderId: '972192467262',
    projectId: 'breadandword',
    databaseURL: 'https://breadandword-default-rtdb.firebaseio.com',
    storageBucket: 'breadandword.firebasestorage.app',
    iosClientId: '972192467262-78hjke0h10fq6lm5kkg3ai1s7qgjujrl.apps.googleusercontent.com',
    iosBundleId: 'com.breadandword',
  );

}